# Generated by Django 3.0.6 on 2020-05-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=5000)),
                ('price', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
